from app.models import db, Product, environment, SCHEMA


def seed_products():
  demo_products = [
    Product(seller_id=1, category="Furniture", name="Malibu Leather Accent Chair", description="Clean, modern lines combine with a relaxed, rustic sensibility in this leather accent chair from our Malibu Collection. Meticulously crafted of wood, the versatile design features flat, wide arms that flow seamlessly into a cube silhouette. Thick seat and back cushions covered in rich leather provide a plush counterpoint to the rigorous geometry, inviting hours of comfortable lounging in your living area, study or bedroom.", details="Square arm.Loose cushions.Frame is expertly crafted from solid oak wood and finished in Gray Wash.Kiln-dried wood helps prevent warping, splitting, cracking and developing mildew.Top-grain leather, aniline-dyed.Leather will lighten and soften with both use and time and develop a rich patina.Leather is a natural product.Variation in color and texture are inherent to each hide; no two pieces are exactly alike.Imported", colors="Browns", price=499),
    Product(seller_id=7, category="Furniture", name="Balboa Upholstered Swivel Armchair", description="With its curved silhouette and generous seat, Balboa gracefully rounds out any space. The swivel design makes this a conversation piece.", details="Barrel arm.Swivel mechanism allows the chair to turn a full 360°; does not tilt or rock.Loose cushions.Frame is expertly crafted from engineered wood.Mortise-and-tenon construction provides strength for added durability.No-sag steel sinuous springs provide cushion support", colors="Whites", price=1099),
    Product(seller_id=7, category="Furniture", name="Sausalito Cane Armoire", description="The texture and finish of Sausalito's driftwood-inspired frame exude relaxed refinement. Crafted of wood and rattan, the textural caning adds a timeless look and airy feel we love. This versatile armoire has an airy, open feel with roomy shelves and drawers that offer ample storage for everything from backup bedding to books. It even has cord cutouts to keep your tech tidy.", details="Expertly crafted of kiln-dried solid meranti wood with sungkai veneers and MDF; drawers are made of solid Pine wood.Crafted of meranti, a tropical hardwood with a long, beautiful grain.Crafted of pine, a gorgeous softwood with a closed grain pattern", colors="Neutrals", price=2299),
    Product(seller_id=7, category="Furniture", name="Malibu Woven Accent Cube", description="Add welcoming warmth and texture to your home with our relaxed Malibu Collection. Using traditional basket-weaving techniques, each spare silhouette is wrapped in handwoven seagrass to create a bright, sun-soaked look that evokes easy-living.", details="Made of Woven Seagrass in a Natural finish.Color variations are inherent in the natural plant fibers used in our Malibu collection. The result may be differences in color tone from that shown.Imported", colors="Neutrals", price=499),
    Product(seller_id=7, category="Furniture", name="Cayman Platform Bed & Headboard", description="A salute to minimalist design, our Cayman Collection has an approachable look and coastal vibe. Crafted of solid wood, the dimensional finish adds a character and warmth to each piece. This strikes a modern balance of sleek right angles and relaxed, gently curved edges.", details="Biscotti and Warm Black finishes are masterfully crafted with kiln-dried mango wood, sustainably sourced.Coffee Bean finish is masterfully crafted with kiln-dried, solid acacia wood.Crafted of mango wood, a sustainably sourced and ultra-durable hardwood", colors="Neutrals", price=1199),
    Product(seller_id=7, category="Furniture", name="Folsom Grand Console Table", description="This streamlined collection highlights the inherent beauty of the wood, giving each piece warm character. Crafted of solid pine, Folsom feels substantial not heavy, and works hard while looking effortless.", details="Made of solid pine wood.Crafted of pine, a gorgeous softwood with a closed grain pattern.Kiln-dried wood helps prevent warping, splitting, cracking and developing mildew.Features a hand applied finish in a choice of Charcoal or Desert Pine (each sold separately).Adjustable levelers help with stability on uneven surfaces.Imported", colors="Neutrals", price=1299),
    Product(seller_id=1, category="Outdoor & Garden", name="Torrey All-Weather Wicker Chaise Lounge", description="With its thick weave and variegated color, Torrey captures the textural beauty of rattan but is also sun, rain, and heat resistant. Gracefully handwoven around a rustproof aluminum frame, the all-weather wicker is wonderfully low maintenance, so you can play outdoors without a care.", details="Hand-woven from durable synthetic material that replicates the look and feel of wicker, but is remarkably resistant to sun, rain, heat and cold.Welded rust-proof aluminum frame.Seat cushion core of resilient Quick Dry® foam is designed for fast water drainage and air circulation", colors="Browns", price=1048),
    Product(seller_id=7, category="Outdoor & Garden", name="Pomona Indoor/Outdoor Concrete C-Table", description="Modern and minimal, Pomona pairs geometric forms with velvety texture to sculptural effect. Hand-poured concrete gives each piece an appeal that endures the test of time and the elements. Its sun-washed tones also make the collection a versatile partner for existing furniture inside or out.", details="Made of cement with fiber; finished in a choice of White or Light Gray.Adjustable levelers provide stability on uneven surfaces.Imported", colors="Whites", price=319),
    Product(seller_id=7, category="Outdoor & Garden", name="Torrey All-Weather Wicker Square Arm Lounge Chair + Pomona Concrete Coffee Table Chat Set", description="A low-maintenance mix of handwoven wicker, hand poured concrete, and grainy acacia combines the weather resistance and relaxed vibe we love for outdoor lounging. Two all-weather wicker lounge chairs have rattan texture in a rich espresso finish to counterbalance crisp white cushions. Pairing them with the smooth shape of our minimal Pomona table in sunwashed tones gives the casual set a collected look.", details="Styled with a full apron, square arm and arched back.Seat cushion core of resilient QuickDry® foam is designed for fast water drainage and air circulation; pillow has polyester fill.Chairs include quick-drying and water-repellent cushions with polyester canvas slipcovers in Natural", colors="Browns", price=1399),
    Product(seller_id=1, category="Bedding", name="Rustic Forest Duvet Cover", description="An image of a stag in a forest has us craving a stay in a snow-covered cabin. We love the rustic palette, a beautiful balance of washed black on a flax backdrop. Crafted of a natural cotton-linen blend, color may vary slightly from piece to piece for a one-of-a-kind look.", details="Front is 50 percent cotton and 50 percent linen; reverse is 100 percent cotton.Duvet features a button closure with inner ties that keep insert in place; sham features an overlap closure.Reverses to solid", colors="Multi", price=169),
    Product(seller_id=7, category="Bedding", name="Belgian Flax Linen Contrast Flange Duvet Cover", description="STANDARD 100 by OEKO-TEX® certified. Tested in an independent lab and verified to be safe from over 350 harmful substances.", details="Linen woven from 100% Belgian flax linen.Reserves to 75 percent cotton and 25 percent linen.Specially washed for a super soft hand-feel", colors="Whites", price=219),
    Product(seller_id=7, category="Bedding", name="Bryce Buffalo Check Cotton Duvet Cover", description="An oversized gingham is a statement look, and this all-cotton buffalo check bedding makes for a casual, comfortable choice. This duvet cover with matching shams can be mixed with solids or a plethora of patterns to create a look all your own.", details="Front fabric of duvet is woven of 100 percent yarn-dyed cotton.Back fabric is woven cotton twill.Duvet reverses to solid natural color", colors="Multi", price=159),
    Product(seller_id=1, category="Bath", name="Holas Handcrafted Freestanding Concrete Bathtub", description="With its perfectly curved form and deep, cradling interior, the Holas Concrete Bathtub provides breathtaking beauty for your self-care rituals. Made from a combination of natural jute fiber and cement, artisans form, polish, finish and seal each tub entirely by hand using contemporary craft techniques, and the thick, insulating walls keep your water at the perfect temperature for longer.", details="Bathtub is handcrafted from concrete and reinforced with natural jute fiber.Finished by hand in a choice of Ash, Earth, Slate or Pearl (each sold separately).Finished with an exclusive low-VOC nano sealer, makes the bathtub exceptionally stain resistant", colors="Neutrals", price=9689),
    Product(seller_id=7, category="Bath", name="Reed Linen Closet", description="With a modern look and a rustic feel, Reed features a minimalist frame crafted of sustainably sourced mango wood. With traditional woodworking details, the keyed-through tenons showcase handcrafted technique, it's storage that doesn't sacrifice style.", details="Expertly crafted from solid Mango wood, aluminum, MDF and finished in Antique Umber.Includes 1 cabinet door with 4 shelves behind door.Magnetic door closure", colors="Browns", price=1049),
    Product(seller_id=7, category="Pillows & Decor", name="Everywhere Velvet Pillows", description="Crafted of pure cotton velvet, these add a touch of luxe wherever they go. In easy-to-layer hues, they are yarn-dyed for lasting color and lustrous sheen and make a solid foundation for endless pillow pairings.", details="Made of 100 percent cotton velvet.Yarn-dyed fiber has incredibly rich color that holds its vibrancy over time.Reverses to same.Zipper closure", colors="Multi", price=49),
    Product(seller_id=7, category="Pillows & Decor", name="Theo Striped Pillow Cover", description="A bold stripe gives this pillow cover its graphic style. Yarn-dyed for deeply saturated color that won't fade, it makes a striking addition to modern and classic spaces alike.", details="Spot clean.Reverses to solid ivory.Zipper closure", colors="Multi", price=42),
    Product(seller_id=7, category="Storage", name="Aubrey Handwoven Basket Collection - Natural", description="Handwoven of rattan and wicker, our Aubrey Basket Collection is both durable and decorative. From housing throws and board games to remotes and dog leashes, Aubrey has a size that does the job beautifully while bringing a feeling of warmth to a space.", details="Handwoven of natural rattan core and wicker.Features a natural finish.Imported", colors="Neutrals", price=159),
    Product(seller_id=7, category="Storage", name="Beachcomber Handwoven Seagrass Oversized Lidded Basket", description="Consciously handcrafted from renewable seagrass, our Beachcomber baskets are a favorite for styling (and organizing) lovely little corners. The braided handles add a decorative touch we love.", details="Handcrafted of round bar, braided natural seagrass and Abaca twine.Features a clear gloss lacquer", colors="Neutrals", price=319),
    Product(seller_id=7, category="Holidays", name="Faux Pre-Lit Aspen Spruce Wreath", description="Spruce up your home this holiday with the look of glowing greenery. This timeless accent is as classic and wintery as hot cocoa and snowmen, and provides the perfect base upon which to add ornaments, holly, or fresh poinsettia blooms each year.", details="For indoor display or in an outside sheltered area.Plug in.Imported", colors="Multi", price=249),
    Product(seller_id=7, category="Holidays", name="Pre-Lit Flocked Vermont Spruce Faux Christmas Tree", description="Make your holidays a lasting memory with a tree that becomes the centerpiece of your celebrations. With its remarkably authentic look, this towering pre-lit Flocked Natural Cut Vermont Spruce brings a festive winter-wonderland feel to your home. Add your treasured ornaments and decorations to make it your own.", details="Made of polyethylene and PVC.Flame resistant.Tree is pre-lit with clear incandescent bulbs.Lights are UL-listed.Imported", colors="Multi", price=999),
    Product(seller_id=7, category="Holidays", name="Light Up Snowy Twiggy Tree", description="A winter wonderland has never been easier thanks to glowing Snowy Pine Trees. They look as enchanting solo as they do in a wintery vignette thanks to warm LED lights along its austere, pine-inspired branches.", details="Made of PVC and metal.Tree is pre-lit with warm white LED lights.Plug in.Flame resistant.For use indoor use only", colors="Multi", price=129),

  ]

  for product in demo_products:
    db.session.add(product)

  db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the Products table. SQLAlchemy doesn"t
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_products():
  if environment == "production":
    db.session.execute(f"TRUNCATE table {SCHEMA}.products RESTART IDENTITY CASCADE;")
  else:
    db.session.execute("DELETE FROM products")

  db.session.commit()
